// Package cubestackgen renders the generated "CubeStack CRD quick reference"
// of the builtin cubestack-platform skill (crd-reference.md) from the vendored
// CubeStack CRD YAMLs under test/e2e/framework/testdata/cubestack-crds.
//
// The map is machine-generated so the skill cannot drift from the CRDs the
// e2e suite installs: hack/gen-cubestack-skill rewrites crd-reference.md and
// the freshness unit test fails CI when the committed file is stale.
package cubestackgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"sigs.k8s.io/yaml"
)

// Header prefixes every generated crd-reference.md.
const Header = "# CubeStack CRD quick reference\n\n" +
	"Generated by make update-cubestack-skill from the vendored CubeStack CRDs\n" +
	"(test/e2e/framework/testdata/cubestack-crds). Do not edit by hand; the\n" +
	"freshness unit test in internal/skill/cubestackgen fails when this file is\n" +
	"stale.\n\n"

// LoadDir reads every *.yaml in dir as an apiextensions CustomResourceDefinition.
func LoadDir(dir string) ([]*apiextensionsv1.CustomResourceDefinition, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, err
	}
	sort.Strings(paths)
	out := make([]*apiextensionsv1.CustomResourceDefinition, 0, len(paths))
	for _, p := range paths {
		raw, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		crd := &apiextensionsv1.CustomResourceDefinition{}
		if err := yaml.Unmarshal(raw, crd); err != nil {
			return nil, fmt.Errorf("decode %s: %w", filepath.Base(p), err)
		}
		out = append(out, crd)
	}
	return out, nil
}

// RenderDocFromDir renders a full crd-reference.md (Header + per-kind map) from
// the CRDs in dir. Deterministic output — kinds and fields are sorted — so the
// committed file and the freshness check always agree byte-for-byte.
func RenderDocFromDir(dir string) (string, error) {
	crds, err := LoadDir(dir)
	if err != nil {
		return "", err
	}
	return Header + render(crds), nil
}

func render(crds []*apiextensionsv1.CustomResourceDefinition) string {
	sort.Slice(crds, func(i, j int) bool {
		return crds[i].Spec.Names.Kind < crds[j].Spec.Names.Kind
	})
	var b strings.Builder
	for _, crd := range crds {
		renderCRD(&b, crd)
	}
	return b.String()
}

func renderCRD(b *strings.Builder, crd *apiextensionsv1.CustomResourceDefinition) {
	names := crd.Spec.Names
	// The vendored CRDs each carry one version; take the first.
	version := crd.Spec.Versions[0]
	spec, ok := version.Schema.OpenAPIV3Schema.Properties["spec"]
	if !ok {
		return
	}
	fmt.Fprintf(b, "## %s\n", names.Kind)
	fmt.Fprintf(b, "- resource `%s.%s`, apiVersion `%s/%s`, scope %s\n",
		names.Plural, crd.Spec.Group, crd.Spec.Group, version.Name, crd.Spec.Scope)
	if len(spec.Required) > 0 {
		fmt.Fprintf(b, "- spec requires: %s\n", strings.Join(spec.Required, ", "))
	}
	b.WriteString("\n")
	walkContainer(b, spec, "spec", 0)
	b.WriteString("\n")
}

// walkContainer emits one row per property of an object / array-of-object
// schema at prefix and recurses one level into container children (so
// spec.resources.* and spec.storage.* are visible, but the file stays shallow).
func walkContainer(b *strings.Builder, schema apiextensionsv1.JSONSchemaProps, prefix string, level int) {
	if len(schema.Properties) == 0 {
		return
	}
	names := make([]string, 0, len(schema.Properties))
	for name := range schema.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		prop := schema.Properties[name]
		path := prefix + "." + name
		fmt.Fprintf(b, "- `%s` — %s\n", path, describe(prop, contains(schema.Required, name)))
		if level >= 1 {
			continue
		}
		if sub, ok := arrayItemSchema(prop); ok {
			walkContainer(b, sub, path+"[]", level+1)
		} else if len(prop.Properties) > 0 {
			walkContainer(b, prop, path, level+1)
		}
	}
}

// arrayItemSchema returns the object schema of an array-of-object property.
func arrayItemSchema(prop apiextensionsv1.JSONSchemaProps) (apiextensionsv1.JSONSchemaProps, bool) {
	if prop.Type == "array" && prop.Items != nil && prop.Items.Schema != nil &&
		len(prop.Items.Schema.Properties) > 0 {
		return *prop.Items.Schema, true
	}
	return apiextensionsv1.JSONSchemaProps{}, false
}

// describe renders "type · required · default · enum · min" for one field.
func describe(prop apiextensionsv1.JSONSchemaProps, required bool) string {
	parts := []string{typeLabel(prop)}
	if required {
		parts = append(parts, "required")
	}
	if len(prop.Enum) > 0 {
		parts = append(parts, "enum: "+joinRaw(prop.Enum))
	}
	if prop.Default != nil {
		parts = append(parts, "default: "+trimRaw(prop.Default.Raw))
	}
	if prop.Minimum != nil {
		parts = append(parts, "min "+trimFloat(*prop.Minimum))
	}
	return strings.Join(parts, " · ")
}

func typeLabel(prop apiextensionsv1.JSONSchemaProps) string {
	if prop.Type == "object" && len(prop.Properties) == 0 {
		return "object"
	}
	if prop.Type == "" {
		if len(prop.Properties) > 0 {
			return "object"
		}
		return "?"
	}
	t := prop.Type
	if prop.Format != "" {
		t = fmt.Sprintf("%s (%s)", t, prop.Format)
	}
	return t
}

func contains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}

// joinRaw joins JSON-scalar raw values (enum entries) comma-separated, with
// string quotes stripped (e.g. ["\"ssh\"","\"vscode\""] -> "ssh, vscode").
func joinRaw(vals []apiextensionsv1.JSON) string {
	out := make([]string, 0, len(vals))
	for _, v := range vals {
		out = append(out, trimRaw(v.Raw))
	}
	return strings.Join(out, ", ")
}

func trimRaw(raw []byte) string {
	s := strings.TrimSpace(string(raw))
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func trimFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%g", f)
}
