#!/usr/bin/env bash
# CubePilot setup: ensure a kind cluster, build images (self-contained in
# Docker), create shared Secrets and deploy components via Helm.
#
# Zero host-machine dependencies by design:
#   * no ~/.openclaw/* config file is ever read;
#   * no pre-built local images (openclaw:local) or host-built bin/ artifacts;
#   * all Go binaries compile inside Docker multi-stage builds.
# Caller-supplied inputs: the platform default LLM apiKey
# (CUBEPILOT_LLM_APIKEY) and optionally a per-user kubeconfig file
# (CUBEPILOT_USER_KUBECONFIG / --user-kubeconfig, dual-kubeconfig issue #19).
# The gateway token and openclaw.json are generated by the operator. This is
# CI-friendly: a fresh runner with docker/kind/kubectl/helm/jq/openssl can
# bring the whole stack up.
#
# Requires: docker, kind, kubectl, jq, helm (v3), openssl.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# ---- inputs (env or flag) ------------------------------------------------
KIND_CLUSTER="${CUBEPILOT_KIND_CLUSTER:-cube}"
NAMESPACE="${CUBEPILOT_NAMESPACE:-cubepilot}"
OPENCLAW_IMAGE_TAG="${CUBEPILOT_OPENCLAW_IMAGE_TAG:-2026.8.1}"
LLM_APIKEY="${CUBEPILOT_LLM_APIKEY:-}"
LLM_ENDPOINT="${CUBEPILOT_LLM_ENDPOINT:-https://api.deepseek.com}"
LLM_MODEL="${CUBEPILOT_LLM_MODEL:-deepseek-v4-flash}"
SKIP_CLUSTER_CREATE="${CUBEPILOT_SKIP_CLUSTER_CREATE:-}"
# Dual-kubeconfig (issue #19 Option B): optional path to a kubeconfig file to
# provision for every operator identity (CUBEPILOT_USERS), mounted as the
# agent's default ~/.kube/config so kubectl runs as the user. When unset, no
# per-user Secret is created and agents fall back to the shared
# agent-kubeconfig (SA) identity -- the historical behaviour.
USER_KUBECONFIG="${CUBEPILOT_USER_KUBECONFIG:-}"
USERS="${CUBEPILOT_USERS:-zhang.wei,li.ming}"
# Built images are registry-addressed (harbor.isuanova.com/suanova); set
# CUBEPILOT_PUSH=1 to push after building (dev machines may lack creds).
IMAGE_REPO="${CUBEPILOT_IMAGE_REPO:-harbor.isuanova.com/suanova}"
IMAGE_TAG="${CUBEPILOT_IMAGE_TAG:-local}"
PUSH="${CUBEPILOT_PUSH:-0}"

while [ $# -gt 0 ]; do
  case "$1" in
    --llm-apikey)         LLM_APIKEY="${2:?--llm-apikey requires a value}"; shift 2 ;;
    --llm-endpoint)       LLM_ENDPOINT="${2:?--llm-endpoint requires a value}"; shift 2 ;;
    --llm-model)          LLM_MODEL="${2:?--llm-model requires a value}"; shift 2 ;;
    --kind-cluster)       KIND_CLUSTER="${2:?--kind-cluster requires a value}"; shift 2 ;;
    --namespace)          NAMESPACE="${2:?--namespace requires a value}"; shift 2 ;;
    --openclaw-image-tag) OPENCLAW_IMAGE_TAG="${2:?--openclaw-image-tag requires a value}"; shift 2 ;;
    --skip-cluster-create) SKIP_CLUSTER_CREATE=1; shift ;;
    --user-kubeconfig)   USER_KUBECONFIG="${2:?--user-kubeconfig requires a path}"; shift 2 ;;
    --push)              PUSH=1; shift ;;
    -h|--help)
      cat <<'EOF'
CubePilot setup -- bring up the stack on a kind cluster with zero host config.

Usage: scripts/setup.sh [flags]

Required:
  CUBEPILOT_LLM_APIKEY / --llm-apikey <apiKey>
      apiKey for the platform default LLM (DeepSeek, the builtin model's
      endpoint). Stored in the cubepilot-llm Secret; the operator renders it
      into the gateway config. A running install can add more LLMs from the
      Portal (Agent Config -> LLM 配置).

Optional:
  CUBEPILOT_LLM_ENDPOINT / --llm-endpoint <url>
      OpenAI-compatible base URL of the platform default LLM (default:
      https://api.deepseek.com). The apiKey still comes from --llm-apikey.
  CUBEPILOT_LLM_MODEL / --llm-model <model>
      Model name (backend model id) of the platform default LLM (default:
      deepseek-v4-flash). Must be in the endpoint's allow-list.
  CUBEPILOT_KIND_CLUSTER / --kind-cluster <name>
      Kind cluster name (default: cube).
  CUBEPILOT_NAMESPACE   / --namespace <ns>
      Target namespace (default: cubepilot).
  CUBEPILOT_OPENCLAW_IMAGE_TAG / --openclaw-image-tag <tag>
      Openclaw base image tag (default: 2026.8.1).
  CUBEPILOT_KIND_CONFIG <path>
      Kind config file used when creating the cluster.
  CUBEPILOT_SKIP_CLUSTER_CREATE / --skip-cluster-create
      Fail instead of creating the kind cluster if it is missing.
  CUBEPILOT_USER_KUBECONFIG / --user-kubeconfig <map>
      Optional. Per-user kubeconfig(s) for the agent's default credentials
      (dual-kubeconfig, issue #19): comma/space list of "user=path" entries, or
      a single bare path when CUBEPILOT_USERS has exactly one identity. When
      unset, agents run as the shared agent-kubeconfig SA.
  CUBEPILOT_PUSH / --push
      Push the four built images to CUBEPILOT_IMAGE_REPO after building.
  CUBEPILOT_IMAGE_REPO / CUBEPILOT_IMAGE_TAG
      Image repository and tag for the built cubepilot images
      (default: harbor.isuanova.com/suanova, local).
EOF
      exit 0 ;;
    *) echo "unknown argument: $1 (see --help)" >&2; exit 1 ;;
  esac
done

log() { printf '\033[1;32m[sync]\033[0m %s\n' "$*"; }

# ---- prerequisites -------------------------------------------------------
command -v docker  >/dev/null || { echo "docker required"; exit 1; }
command -v kind    >/dev/null || { echo "kind required"; exit 1; }
command -v kubectl >/dev/null || { echo "kubectl required"; exit 1; }
command -v jq      >/dev/null || { echo "jq required"; exit 1; }
command -v helm    >/dev/null || { echo "helm required"; exit 1; }
command -v openssl >/dev/null || { echo "openssl required"; exit 1; }

[ -n "$LLM_APIKEY" ] || {
  echo "error: CUBEPILOT_LLM_APIKEY is required (the platform default LLM apiKey). See --help." >&2
  exit 1
}

# ---- kind cluster bootstrap ----------------------------------------------
if ! kind get clusters 2>/dev/null | grep -qx "$KIND_CLUSTER"; then
  if [ -n "$SKIP_CLUSTER_CREATE" ]; then
    echo "error: kind cluster '$KIND_CLUSTER' missing and --skip-cluster-create is set" >&2
    exit 1
  fi
  log "creating kind cluster '$KIND_CLUSTER'"
  kind create cluster --name "$KIND_CLUSTER" ${CUBEPILOT_KIND_CONFIG:+--config "$CUBEPILOT_KIND_CONFIG"}
else
  log "kind cluster '$KIND_CLUSTER' already exists"
fi

# ---- build images (self-contained in Docker) -----------------------------
log "building images ($IMAGE_REPO, tag $IMAGE_TAG)"
docker build -t "$IMAGE_REPO/cubepilot-openclaw:$IMAGE_TAG" --build-arg OPENCLAW_IMAGE_TAG="$OPENCLAW_IMAGE_TAG" \
  -f "$REPO_DIR/deploy/openclaw-image.Dockerfile" "$REPO_DIR"
docker build -t "$IMAGE_REPO/cubepilot-operator:$IMAGE_TAG" -f "$REPO_DIR/deploy/operator-image.Dockerfile" "$REPO_DIR"
docker build -t "$IMAGE_REPO/cubepilot-api:$IMAGE_TAG"      -f "$REPO_DIR/deploy/api-image.Dockerfile"      "$REPO_DIR"
docker build -t "$IMAGE_REPO/cubepilot-web:$IMAGE_TAG"      -f "$REPO_DIR/web/Dockerfile"                  "$REPO_DIR/web"

if [ "$PUSH" = "1" ]; then
  log "pushing images to $IMAGE_REPO"
  docker push "$IMAGE_REPO/cubepilot-openclaw:$IMAGE_TAG"
  docker push "$IMAGE_REPO/cubepilot-operator:$IMAGE_TAG"
  docker push "$IMAGE_REPO/cubepilot-api:$IMAGE_TAG"
  docker push "$IMAGE_REPO/cubepilot-web:$IMAGE_TAG"
fi

log "loading images into kind ($KIND_CLUSTER)"
kind load docker-image "$IMAGE_REPO/cubepilot-openclaw:$IMAGE_TAG" "$IMAGE_REPO/cubepilot-operator:$IMAGE_TAG" \
  "$IMAGE_REPO/cubepilot-api:$IMAGE_TAG" "$IMAGE_REPO/cubepilot-web:$IMAGE_TAG" --name "$KIND_CLUSTER"

log "creating namespace + RBAC"
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

log "creating shared secrets"
kubectl -n "$NAMESPACE" create secret generic agent-kubeconfig \
  --from-file=config="$REPO_DIR/deploy/agent-kubeconfig.yaml" \
  --dry-run=client -o yaml | kubectl apply -f -

# Dual-kubeconfig (issue #19 Option B): provision one kubeconfig Secret per
# operator identity so agents run user-facing kubectl as the user. Sanitize
# mirrors k8s.Sanitize. Optional -- absent per-user Secrets mean the operator
# falls back to the shared agent-kubeconfig (SA) identity.
# CUBEPILOT_USER_KUBECONFIG is a comma/space list of "<user>=<path>" mappings
# (one kubeconfig per operator identity), or a single bare "<path>" when there
# is exactly one operator identity. Each user's Secret is named after
# k8s.UserKubeconfigSecretFor: sanitized identity + 8-hex sha256 of the raw
# identity, so distinct users always get distinct Secrets.
if [ -n "$USER_KUBECONFIG" ]; then
  log "creating per-user kubeconfig Secrets (dual-kubeconfig)"
  user_count=$(awk -F, '{print NF}' <<< "$USERS")
  IFS=',' read -ra ENTRIES <<< "$USER_KUBECONFIG"
  for e in "${ENTRIES[@]}"; do
    e="${e//[[:space:]]/}"
    [ -n "$e" ] || continue
    if [[ "$e" == *=* ]]; then
      u="${e%%=*}"; path="${e#*=}"
    else
      [ "$user_count" -eq 1 ] || {
        echo "error: a bare --user-kubeconfig path requires exactly one identity in CUBEPILOT_USERS; use 'user=path' entries for multiple users" >&2
        exit 1
      }
      u="${USERS%% *,*}"
      path="$e"
    fi
    [ -f "$path" ] || { echo "error: --user-kubeconfig file not found: $path" >&2; exit 1; }
    s="$(printf '%s' "$u" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9-]+/-/g; s/^-+|-+$//g')"
    [ -n "$s" ] || s=user
    h="$(printf '%s' "$u" | sha256sum | cut -c1-8)"
    name="${s}-kubeconfig-${h}"
    kubectl -n "$NAMESPACE" create secret generic "$name" \
      --from-file=config="$path" \
      --dry-run=client -o yaml | kubectl apply -f -
    log "  $name <- $path (user: $u)"
  done
fi

# Platform default LLM credential (the builtin AgentTemplate references it; the
# operator renders it into the gateway config). The openclaw-config Secret
# (gateway token + rendered openclaw.json) is created by the operator.
kubectl -n "$NAMESPACE" create secret generic cubepilot-llm \
  --from-literal=apiKey="$LLM_APIKEY" \
  --dry-run=client -o yaml | kubectl apply -f -

log "deploying components via Helm (CRDs ship in the chart crds/ dir)"
helm upgrade --install cubepilot "$REPO_DIR/deploy/charts/cubepilot" -n "$NAMESPACE" \
  --set agents.image="$IMAGE_REPO/cubepilot-openclaw:$IMAGE_TAG" \
  --set agents.llmEndpoint="$LLM_ENDPOINT" \
  --set agents.llmModel="$LLM_MODEL" \
  --set operator.image="$IMAGE_REPO/cubepilot-operator:$IMAGE_TAG" \
  --set api.image="$IMAGE_REPO/cubepilot-api:$IMAGE_TAG" \
  --set web.image="$IMAGE_REPO/cubepilot-web:$IMAGE_TAG"

log "done. expose the portal with:"
log "  kubectl -n $NAMESPACE port-forward svc/cubepilot 8080:8080"
log "then open http://127.0.0.1:8080"
